# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62576c8b367a5662b050d779e62e4d3e95d4774a7200ba66653410652720a8d95c2d42cb04392127ae597a9cc45520084a217825adccc561cb08d041bb0f5546

test:
  secret_key_base: 8d25d05a753d2b2b4334ef8458de8afe46995b65256eea35048d31c266367ffb565866bc3fbdac01cb7dccb8f11631eb76d78b887787f2e7383881beb8d42e29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
